# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-05 13:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_strings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationstring',
            name='text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='translationstring',
            name='text_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='translationstring',
            name='text_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='translationstring',
            name='text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='translationstring',
            name='text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='translationstring',
            name='text_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
