# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-08 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_strings', '0002_auto_20190305_1351'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationstring',
            name='text_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='translationstring',
            name='text_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='translationstring',
            name='text_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='translationstring',
            name='text_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
