# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-08 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_strings', '0003_auto_20190408_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationstring',
            name='text_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
