# Generated by Django 2.2 on 2022-03-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('translation_strings', '0006_auto_20210928_2328'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translationstring',
            name='frontend_text_ar',
        ),
        migrations.RemoveField(
            model_name='translationstring',
            name='frontend_text_bn',
        ),
        migrations.RemoveField(
            model_name='translationstring',
            name='frontend_text_es',
        ),
        migrations.RemoveField(
            model_name='translationstring',
            name='frontend_text_fr',
        ),
        migrations.RemoveField(
            model_name='translationstring',
            name='frontend_text_ht',
        ),
        migrations.RemoveField(
            model_name='translationstring',
            name='frontend_text_ko',
        ),
        migrations.RemoveField(
            model_name='translationstring',
            name='frontend_text_pl',
        ),
        migrations.RemoveField(
            model_name='translationstring',
            name='frontend_text_ru',
        ),
        migrations.RemoveField(
            model_name='translationstring',
            name='frontend_text_ur',
        ),
        migrations.RemoveField(
            model_name='translationstring',
            name='frontend_text_zh_hant',
        ),
    ]
