# Generated by Django 2.2 on 2022-11-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('translation_strings', '0007_auto_20220322_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='translationstring',
            name='frontend_text_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='translationstring',
            name='frontend_text_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='translationstring',
            name='frontend_text_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='translationstring',
            name='frontend_text_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='translationstring',
            name='frontend_text_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='translationstring',
            name='frontend_text_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='translationstring',
            name='frontend_text_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='translationstring',
            name='frontend_text_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='translationstring',
            name='frontend_text_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='translationstring',
            name='frontend_text_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
