# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 13:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_stories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narrativesection',
            name='bar_chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='narrative_bar_chart', to='visualizations.DataStoryBarChart'),
        ),
        migrations.AlterField(
            model_name='narrativesection',
            name='dual_axis_line_and_column',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='narrative_axis_chart', to='visualizations.DataStoryDualAxisLineAndColumn'),
        ),
        migrations.AlterField(
            model_name='narrativesection',
            name='map_chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='narrative_map', to='visualizations.DataStoryMapChart'),
        ),
        migrations.AlterField(
            model_name='narrativesection',
            name='sankey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='narrative_sankey', to='visualizations.DataStorySankey'),
        ),
        migrations.AlterField(
            model_name='narrativesection',
            name='stacked_bar_chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='narrative_stacked_bar_chart', to='visualizations.DataStoryStackedBarChart'),
        ),
    ]
