# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-29 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_stories', '0003_auto_20190301_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastory',
            name='icon',
            field=models.CharField(blank=True, choices=[('Column', 'Column Icon'), ('Dots', 'Dots Icon'), ('Histogram', 'Histogram Icon'), ('Bar', 'Bar Icon'), ('Sankey', 'Sankey Icon')], default=('Column', 'Column Icon'), max_length=255, null=True),
        ),
    ]
