# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-01 17:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_stories', '0004_auto_20190329_1627'),
    ]

    operations = [
        migrations.AlterField(
            model_name='narrativesection',
            name='map_chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='narrative_map', to='visualizations.MapChart'),
        ),
    ]
