# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-25 17:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0022_datastorylinechart_datastorylinechartdataset'),
        ('data_stories', '0006_auto_20190408_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrativesection',
            name='line_chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='narrative_line_chart', to='visualizations.DataStoryLineChart'),
        ),
    ]
