# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-08 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_stories', '0007_narrativesection_line_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastory',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastory',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='narrativesection',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='narrativesection',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
