# Generated by Django 2.2 on 2021-02-01 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_stories', '0009_datastorytranslation'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastorytranslation',
            name='_tdescription',
            field=models.TextField(default='a'),
            preserve_default=False,
        ),
    ]
