# Generated by Django 2.2 on 2021-02-01 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_stories', '0011_migrate_translatable_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastory',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='description_bn',
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='description_en',
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='description_ht',
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='description_ko',
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='description_pl',
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='description_ur',
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='description_zh_hant',
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='title_bn',
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='title_ht',
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='title_ko',
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='title_ur',
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='title_zh_hant',
        ),
    ]
