# Generated by Django 2.2 on 2021-02-02 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_stories', '0012_auto_20210201_1756'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='datastory',
            name='title',
        ),
    ]
