# Generated by Django 2.2 on 2021-02-02 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_stories', '0013_auto_20210202_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datastorytranslation',
            old_name='_tdescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='datastorytranslation',
            old_name='_ttitle',
            new_name='title',
        ),
    ]
