# Generated by Django 2.2 on 2021-08-19 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_stories', '0016_auto_20210223_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastory',
            name='icon',
            field=models.CharField(blank=True, choices=[('Column', 'Column Icon'), ('Dots', 'Dots Icon'), ('Histogram', 'Histogram Icon'), ('Bar', 'Bar Icon'), ('Sankey', 'Sankey Icon')], default=('Column', 'Column Icon'), max_length=255),
        ),
    ]
