# Generated by Django 2.2 on 2021-08-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_stories', '0017_auto_20210819_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastory',
            name='icon',
            field=models.CharField(blank=True, choices=[('Column', 'Column Icon'), ('Dots', 'Dots Icon'), ('Histogram', 'Histogram Icon'), ('Bar', 'Bar Icon'), ('Sankey', 'Sankey Icon')], default=('Column', 'Column Icon'), max_length=255, null=True),
        ),
    ]
