# Generated by Django 2.2 on 2022-03-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_stories', '0018_auto_20210825_0919'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='narrativesection',
            name='description_ar',
        ),
        migrations.RemoveField(
            model_name='narrativesection',
            name='description_bn',
        ),
        migrations.RemoveField(
            model_name='narrativesection',
            name='description_es',
        ),
        migrations.RemoveField(
            model_name='narrativesection',
            name='description_fr',
        ),
        migrations.RemoveField(
            model_name='narrativesection',
            name='description_ht',
        ),
        migrations.RemoveField(
            model_name='narrativesection',
            name='description_ko',
        ),
        migrations.RemoveField(
            model_name='narrativesection',
            name='description_pl',
        ),
        migrations.RemoveField(
            model_name='narrativesection',
            name='description_ru',
        ),
        migrations.RemoveField(
            model_name='narrativesection',
            name='description_ur',
        ),
        migrations.RemoveField(
            model_name='narrativesection',
            name='description_zh_hant',
        ),
        migrations.RemoveField(
            model_name='narrativesection',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='narrativesection',
            name='title_bn',
        ),
        migrations.RemoveField(
            model_name='narrativesection',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='narrativesection',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='narrativesection',
            name='title_ht',
        ),
        migrations.RemoveField(
            model_name='narrativesection',
            name='title_ko',
        ),
        migrations.RemoveField(
            model_name='narrativesection',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='narrativesection',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='narrativesection',
            name='title_ur',
        ),
        migrations.RemoveField(
            model_name='narrativesection',
            name='title_zh_hant',
        ),
        migrations.AddField(
            model_name='datastory',
            name='updated_date',
            field=models.DateField(blank=True, db_index=True, help_text='Updated Date', null=True, verbose_name='Updated Date'),
        ),
    ]
