# Generated by Django 2.2 on 2022-11-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_stories', '0019_auto_20220322_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrativesection',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='narrativesection',
            name='description_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='narrativesection',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='narrativesection',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='narrativesection',
            name='description_ht',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='narrativesection',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='narrativesection',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='narrativesection',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='narrativesection',
            name='description_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='narrativesection',
            name='description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='narrativesection',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='narrativesection',
            name='title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='narrativesection',
            name='title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='narrativesection',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='narrativesection',
            name='title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='narrativesection',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='narrativesection',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='narrativesection',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='narrativesection',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='narrativesection',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
