# Generated by Django 2.2 on 2023-07-05 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0039_datastoryscatterchart_datastoryscatterchartdataset_scatterchart'),
        ('data_stories', '0020_auto_20221129_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrativesection',
            name='scatter_chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='narrative_scatter_chart', to='visualizations.DataStoryScatterChart'),
        ),
    ]
