# Generated by Django 2.2 on 2023-07-13 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0041_auto_20230713_1010'),
        ('data_stories', '0021_narrativesection_scatter_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='narrativesection',
            name='boxplot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='narrative_boxplot', to='visualizations.DataStoryBoxplot'),
        ),
    ]
