# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 14:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
        ('common_metrics', '0005_auto_20190221_1714'),
        ('visualizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='barchart',
            name='agency',
            field=models.ManyToManyField(to='programs.Agency'),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='agency',
            field=models.ManyToManyField(to='programs.Agency'),
        ),
        migrations.AddField(
            model_name='mapchart',
            name='agency',
            field=models.ManyToManyField(to='programs.Agency'),
        ),
        migrations.AddField(
            model_name='sankey',
            name='agency',
            field=models.ManyToManyField(to='programs.Agency'),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='agency',
            field=models.ManyToManyField(to='programs.Agency'),
        ),
        migrations.RemoveField(
            model_name='barchart',
            name='metric_category',
        ),
        migrations.AddField(
            model_name='barchart',
            name='metric_category',
            field=models.ManyToManyField(blank=True, null=True, to='common_metrics.MetricCategory'),
        ),
        migrations.RemoveField(
            model_name='dualaxislineandcolumn',
            name='metric_category',
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='metric_category',
            field=models.ManyToManyField(blank=True, null=True, to='common_metrics.MetricCategory'),
        ),
        migrations.RemoveField(
            model_name='mapchart',
            name='metric_category',
        ),
        migrations.AddField(
            model_name='mapchart',
            name='metric_category',
            field=models.ManyToManyField(blank=True, null=True, to='common_metrics.MetricCategory'),
        ),
        migrations.RemoveField(
            model_name='sankey',
            name='metric_category',
        ),
        migrations.AddField(
            model_name='sankey',
            name='metric_category',
            field=models.ManyToManyField(blank=True, null=True, to='common_metrics.MetricCategory'),
        ),
        migrations.RemoveField(
            model_name='stackedbarchart',
            name='metric_category',
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='metric_category',
            field=models.ManyToManyField(blank=True, null=True, to='common_metrics.MetricCategory'),
        ),
    ]
