# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-26 11:06
from __future__ import unicode_literals

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0001_initial'),
    ]

    operations = []
