# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0002_auto_20190226_1106'),
    ]

    operations = [
        migrations.AddField(
            model_name='barchart',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='short_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='x_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='y_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='short_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='x_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='y_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='short_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='x_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='y_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorymapchart',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorymapchart',
            name='short_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorymapchart',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorymapchart',
            name='x_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorymapchart',
            name='y_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='short_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='x_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='y_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='short_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='x_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='y_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='short_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='x_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='y_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mapchart',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mapchart',
            name='short_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mapchart',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mapchart',
            name='x_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mapchart',
            name='y_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='short_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='x_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='y_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='short_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='x_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='y_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
