# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 14:19
from __future__ import unicode_literals

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('common_metrics', '0005_auto_20190221_1714'),
        ('programs', '0001_initial'),
        ('visualizations', '0002_auto_20190301_1414'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dualaxislineandcolumn',
            name='agency',
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='line_agency',
            field=models.ManyToManyField(related_name='line_agency', to='programs.Agency'),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='line_aggregate_by',
            field=models.CharField(choices=[('program', 'program'), ('agency', 'agency'), ('subgroup', 'subgroup')], default='1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='line_metric_category',
            field=models.ManyToManyField(blank=True, null=True, related_name='line_metric_category', to='common_metrics.MetricCategory'),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='line_metric_subgroup',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='line_metric_category', chained_model_field='line_metric_category', null=True, related_name='line_metric_subgroup', to='common_metrics.MetricCategorySubGroup'),
        ),
    ]
