# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 19:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0003_auto_20190301_1135'),
        ('visualizations', '0004_dualaxislineandcolumn_agency'),
    ]

    operations = [
    ]
