# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0004_auto_20190301_1726'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStoryStackedBarChartDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('series_name', models.TextField()),
                ('series_data', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='StackedBarChartDataSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('series_name', models.TextField()),
                ('series_data', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='barchart',
            name='categories',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='categories',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='datastorybarchartdataset',
            name='bar_chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualizations.DataStoryBarChart'),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='categories',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='categories',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='dualaxislineandcolumn',
            name='categories',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='stackedbarchart',
            name='categories',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='stackedbarchartdataset',
            name='bar_chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualizations.StackedBarChart'),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchartdataset',
            name='bar_chart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='visualizations.DataStoryStackedBarChart'),
        ),
    ]
