# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-02 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0005_merge_20190301_1939'),
        ('visualizations', '0005_auto_20190301_1837'),
    ]

    operations = [
    ]
