# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-05 10:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0006_merge_20190302_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barchartdataset',
            name='bar_chart',
        ),
        migrations.RemoveField(
            model_name='dualaxislineandcolumndataset',
            name='dual_axis_line_and_column',
        ),
        migrations.RemoveField(
            model_name='sankeydataset',
            name='sankey',
        ),
        migrations.RemoveField(
            model_name='stackedbarchartdataset',
            name='bar_chart',
        ),
        migrations.RemoveField(
            model_name='barchart',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='dualaxislineandcolumn',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='stackedbarchart',
            name='categories',
        ),
        migrations.DeleteModel(
            name='BarChartDataSet',
        ),
        migrations.DeleteModel(
            name='DualAxisLineAndColumnDataSet',
        ),
        migrations.DeleteModel(
            name='SankeyDataSet',
        ),
        migrations.DeleteModel(
            name='StackedBarChartDataSet',
        ),
    ]
