# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-05 14:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0007_auto_20190305_1059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='barchart',
            name='data_set',
        ),
        migrations.RemoveField(
            model_name='datastorybarchart',
            name='data_set',
        ),
        migrations.RemoveField(
            model_name='datastorydualaxislineandcolumn',
            name='data_set',
        ),
        migrations.RemoveField(
            model_name='datastorymapchart',
            name='data_set',
        ),
        migrations.RemoveField(
            model_name='datastorysankey',
            name='data_set',
        ),
        migrations.RemoveField(
            model_name='datastorystackedbarchart',
            name='data_set',
        ),
        migrations.RemoveField(
            model_name='dualaxislineandcolumn',
            name='data_set',
        ),
        migrations.RemoveField(
            model_name='mapchart',
            name='data_set',
        ),
        migrations.RemoveField(
            model_name='sankey',
            name='data_set',
        ),
        migrations.RemoveField(
            model_name='stackedbarchart',
            name='data_set',
        ),
        migrations.AlterField(
            model_name='datastorybarchartdataset',
            name='series_data',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='datastorybarchartdataset',
            name='series_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='datastorybarchartdataset',
            name='series_name_ar',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchartdataset',
            name='series_name_bn',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchartdataset',
            name='series_name_en',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchartdataset',
            name='series_name_es',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchartdataset',
            name='series_name_fr',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchartdataset',
            name='series_name_ru',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumndataset',
            name='series_data',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumndataset',
            name='series_name',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumndataset',
            name='series_name_ar',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumndataset',
            name='series_name_bn',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumndataset',
            name='series_name_en',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumndataset',
            name='series_name_es',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumndataset',
            name='series_name_fr',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumndataset',
            name='series_name_ru',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankeydataset',
            name='sankey_count',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='datastorysankeydataset',
            name='sankey_from',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='datastorysankeydataset',
            name='sankey_from_ar',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankeydataset',
            name='sankey_from_bn',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankeydataset',
            name='sankey_from_en',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankeydataset',
            name='sankey_from_es',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankeydataset',
            name='sankey_from_fr',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankeydataset',
            name='sankey_from_ru',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankeydataset',
            name='sankey_step',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='datastorysankeydataset',
            name='sankey_to',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='datastorysankeydataset',
            name='sankey_to_ar',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankeydataset',
            name='sankey_to_bn',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankeydataset',
            name='sankey_to_en',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankeydataset',
            name='sankey_to_es',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankeydataset',
            name='sankey_to_fr',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankeydataset',
            name='sankey_to_ru',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchartdataset',
            name='series_data',
            field=models.CharField(max_length=5000),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchartdataset',
            name='series_name',
            field=models.CharField(max_length=1000),
        ),
    ]
