# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-07 12:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0012_auto_20190306_1842'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastorysankeydataset',
            name='sankey_count',
        ),
        migrations.RemoveField(
            model_name='datastorysankeydataset',
            name='sankey_from',
        ),
        migrations.RemoveField(
            model_name='datastorysankeydataset',
            name='sankey_from_ar',
        ),
        migrations.RemoveField(
            model_name='datastorysankeydataset',
            name='sankey_from_bn',
        ),
        migrations.RemoveField(
            model_name='datastorysankeydataset',
            name='sankey_from_en',
        ),
        migrations.RemoveField(
            model_name='datastorysankeydataset',
            name='sankey_from_es',
        ),
        migrations.RemoveField(
            model_name='datastorysankeydataset',
            name='sankey_from_fr',
        ),
        migrations.RemoveField(
            model_name='datastorysankeydataset',
            name='sankey_from_ru',
        ),
        migrations.RemoveField(
            model_name='datastorysankeydataset',
            name='sankey_step',
        ),
        migrations.RemoveField(
            model_name='datastorysankeydataset',
            name='sankey_to',
        ),
        migrations.RemoveField(
            model_name='datastorysankeydataset',
            name='sankey_to_ar',
        ),
        migrations.RemoveField(
            model_name='datastorysankeydataset',
            name='sankey_to_bn',
        ),
        migrations.RemoveField(
            model_name='datastorysankeydataset',
            name='sankey_to_en',
        ),
        migrations.RemoveField(
            model_name='datastorysankeydataset',
            name='sankey_to_es',
        ),
        migrations.RemoveField(
            model_name='datastorysankeydataset',
            name='sankey_to_fr',
        ),
        migrations.RemoveField(
            model_name='datastorysankeydataset',
            name='sankey_to_ru',
        ),
        migrations.AddField(
            model_name='datastorysankeydataset',
            name='sankey_line',
            field=models.TextField(default='a', max_length=1000),
            preserve_default=False,
        ),
    ]
