# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-13 11:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0013_auto_20190307_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barchart',
            name='short_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='barchart',
            name='short_title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='barchart',
            name='short_title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='barchart',
            name='short_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='barchart',
            name='short_title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='barchart',
            name='short_title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='barchart',
            name='short_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='short_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='short_title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='short_title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='short_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='short_title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='short_title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='short_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='short_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='short_title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='short_title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='short_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='short_title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='short_title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='short_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorymapchart',
            name='short_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datastorymapchart',
            name='short_title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorymapchart',
            name='short_title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorymapchart',
            name='short_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorymapchart',
            name='short_title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorymapchart',
            name='short_title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorymapchart',
            name='short_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankey',
            name='short_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datastorysankey',
            name='short_title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankey',
            name='short_title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankey',
            name='short_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankey',
            name='short_title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankey',
            name='short_title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankey',
            name='short_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='short_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='short_title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='short_title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='short_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='short_title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='short_title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='short_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dualaxislineandcolumn',
            name='short_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='dualaxislineandcolumn',
            name='short_title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dualaxislineandcolumn',
            name='short_title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dualaxislineandcolumn',
            name='short_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dualaxislineandcolumn',
            name='short_title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dualaxislineandcolumn',
            name='short_title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dualaxislineandcolumn',
            name='short_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mapchart',
            name='short_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='mapchart',
            name='short_title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mapchart',
            name='short_title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mapchart',
            name='short_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mapchart',
            name='short_title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mapchart',
            name='short_title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mapchart',
            name='short_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sankey',
            name='short_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='sankey',
            name='short_title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sankey',
            name='short_title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sankey',
            name='short_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sankey',
            name='short_title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sankey',
            name='short_title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sankey',
            name='short_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stackedbarchart',
            name='short_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='stackedbarchart',
            name='short_title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stackedbarchart',
            name='short_title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stackedbarchart',
            name='short_title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stackedbarchart',
            name='short_title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stackedbarchart',
            name='short_title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stackedbarchart',
            name='short_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
