# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-21 15:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0015_auto_20190315_1506'),
    ]

    operations = [
        migrations.AlterField(
            model_name='barchart',
            name='short_title',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255),
        ),
        migrations.AlterField(
            model_name='barchart',
            name='short_title_ar',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='barchart',
            name='short_title_bn',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='barchart',
            name='short_title_en',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='barchart',
            name='short_title_es',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='barchart',
            name='short_title_fr',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='barchart',
            name='short_title_ru',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='categories',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54'),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='categories_ar',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='categories_bn',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='categories_en',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='categories_es',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='categories_fr',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='categories_ru',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='short_title',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='short_title_ar',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='short_title_bn',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='short_title_en',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='short_title_es',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='short_title_fr',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='short_title_ru',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchartdataset',
            name='series_data',
            field=models.TextField(help_text='This should be all data points for the individual series. They should be comma seperated and surrounded by brackets and have the same number of entries as categories. For Example: [80, 70, 55, 92]'),
        ),
        migrations.AlterField(
            model_name='datastorybarchartdataset',
            name='series_name',
            field=models.CharField(help_text="This will be the individual bar's title in the legend. For example: Part-Time", max_length=500),
        ),
        migrations.AlterField(
            model_name='datastorybarchartdataset',
            name='series_name_ar',
            field=models.CharField(help_text="This will be the individual bar's title in the legend. For example: Part-Time", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchartdataset',
            name='series_name_bn',
            field=models.CharField(help_text="This will be the individual bar's title in the legend. For example: Part-Time", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchartdataset',
            name='series_name_en',
            field=models.CharField(help_text="This will be the individual bar's title in the legend. For example: Part-Time", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchartdataset',
            name='series_name_es',
            field=models.CharField(help_text="This will be the individual bar's title in the legend. For example: Part-Time", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchartdataset',
            name='series_name_fr',
            field=models.CharField(help_text="This will be the individual bar's title in the legend. For example: Part-Time", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='datastorybarchartdataset',
            name='series_name_ru',
            field=models.CharField(help_text="This will be the individual bar's title in the legend. For example: Part-Time", max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='categories',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. It should not include the line category For example: Under 16,16 to 19,20 to 24,25 to 54'),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='categories_ar',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. It should not include the line category For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='categories_bn',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. It should not include the line category For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='categories_en',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. It should not include the line category For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='categories_es',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. It should not include the line category For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='categories_fr',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. It should not include the line category For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='categories_ru',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. It should not include the line category For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='short_title',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='short_title_ar',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='short_title_bn',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='short_title_en',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='short_title_es',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='short_title_fr',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='short_title_ru',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorymapchart',
            name='short_title',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255),
        ),
        migrations.AlterField(
            model_name='datastorymapchart',
            name='short_title_ar',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorymapchart',
            name='short_title_bn',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorymapchart',
            name='short_title_en',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorymapchart',
            name='short_title_es',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorymapchart',
            name='short_title_fr',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorymapchart',
            name='short_title_ru',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankey',
            name='short_title',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255),
        ),
        migrations.AlterField(
            model_name='datastorysankey',
            name='short_title_ar',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankey',
            name='short_title_bn',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankey',
            name='short_title_en',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankey',
            name='short_title_es',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankey',
            name='short_title_fr',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorysankey',
            name='short_title_ru',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='categories',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54'),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='categories_ar',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='categories_bn',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='categories_en',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='categories_es',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='categories_fr',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='categories_ru',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='short_title',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='short_title_ar',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='short_title_bn',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='short_title_en',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='short_title_es',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='short_title_fr',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='short_title_ru',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dualaxislineandcolumn',
            name='short_title',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255),
        ),
        migrations.AlterField(
            model_name='dualaxislineandcolumn',
            name='short_title_ar',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dualaxislineandcolumn',
            name='short_title_bn',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dualaxislineandcolumn',
            name='short_title_en',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dualaxislineandcolumn',
            name='short_title_es',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dualaxislineandcolumn',
            name='short_title_fr',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='dualaxislineandcolumn',
            name='short_title_ru',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mapchart',
            name='short_title',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255),
        ),
        migrations.AlterField(
            model_name='mapchart',
            name='short_title_ar',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mapchart',
            name='short_title_bn',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mapchart',
            name='short_title_en',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mapchart',
            name='short_title_es',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mapchart',
            name='short_title_fr',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='mapchart',
            name='short_title_ru',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sankey',
            name='short_title',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255),
        ),
        migrations.AlterField(
            model_name='sankey',
            name='short_title_ar',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sankey',
            name='short_title_bn',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sankey',
            name='short_title_en',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sankey',
            name='short_title_es',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sankey',
            name='short_title_fr',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='sankey',
            name='short_title_ru',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stackedbarchart',
            name='short_title',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255),
        ),
        migrations.AlterField(
            model_name='stackedbarchart',
            name='short_title_ar',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stackedbarchart',
            name='short_title_bn',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stackedbarchart',
            name='short_title_en',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stackedbarchart',
            name='short_title_es',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stackedbarchart',
            name='short_title_fr',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='stackedbarchart',
            name='short_title_ru',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
    ]
