# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-01 17:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_stories', '0005_auto_20190401_1708'),
        ('visualizations', '0016_auto_20190321_1510'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastorycoordinate',
            name='map_chart',
        ),
        migrations.RemoveField(
            model_name='mapchart',
            name='agency',
        ),
        migrations.RemoveField(
            model_name='mapchart',
            name='aggregate_by',
        ),
        migrations.RemoveField(
            model_name='mapchart',
            name='metric_category',
        ),
        migrations.RemoveField(
            model_name='mapchart',
            name='metric_name',
        ),
        migrations.RemoveField(
            model_name='mapchart',
            name='metric_subgroup',
        ),
        migrations.RemoveField(
            model_name='mapchart',
            name='x_axis_title',
        ),
        migrations.RemoveField(
            model_name='mapchart',
            name='x_axis_title_ar',
        ),
        migrations.RemoveField(
            model_name='mapchart',
            name='x_axis_title_bn',
        ),
        migrations.RemoveField(
            model_name='mapchart',
            name='x_axis_title_en',
        ),
        migrations.RemoveField(
            model_name='mapchart',
            name='x_axis_title_es',
        ),
        migrations.RemoveField(
            model_name='mapchart',
            name='x_axis_title_fr',
        ),
        migrations.RemoveField(
            model_name='mapchart',
            name='x_axis_title_ru',
        ),
        migrations.RemoveField(
            model_name='mapchart',
            name='y_axis_title',
        ),
        migrations.RemoveField(
            model_name='mapchart',
            name='y_axis_title_ar',
        ),
        migrations.RemoveField(
            model_name='mapchart',
            name='y_axis_title_bn',
        ),
        migrations.RemoveField(
            model_name='mapchart',
            name='y_axis_title_en',
        ),
        migrations.RemoveField(
            model_name='mapchart',
            name='y_axis_title_es',
        ),
        migrations.RemoveField(
            model_name='mapchart',
            name='y_axis_title_fr',
        ),
        migrations.RemoveField(
            model_name='mapchart',
            name='y_axis_title_ru',
        ),
        migrations.AddField(
            model_name='mapchart',
            name='shapefile',
            field=models.TextField(blank=True),
        ),
        migrations.DeleteModel(
            name='DataStoryCoordinate',
        ),
        migrations.DeleteModel(
            name='DataStoryMapChart',
        ),
    ]
