# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-02 16:14
from __future__ import unicode_literals

from django.db import migrations, models
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0017_auto_20190401_1708'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumndataset',
            name='dual_axis_type',
            field=models.CharField(choices=[('line', 'line'), ('bar', 'bar')], max_length=255),
        ),
        migrations.AlterField(
            model_name='dualaxislineandcolumn',
            name='dual_axis_type',
            field=models.CharField(choices=[('line', 'line'), ('bar', 'bar')], max_length=255),
        ),
        migrations.AlterField(
            model_name='dualaxislineandcolumn',
            name='line_aggregate_by',
            field=models.CharField(choices=[('agency', 'agency'), ('subgroup', 'subgroup')], max_length=255),
        ),
        migrations.AlterField(
            model_name='dualaxislineandcolumn',
            name='line_metric_subgroup',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='line_metric_category', chained_model_field='metric_category', null=True, related_name='line_metric_subgroup', to='common_metrics.MetricCategorySubGroup'),
        ),
    ]
