# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-08 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0019_auto_20190403_1808'),
    ]

    operations = [
        migrations.AddField(
            model_name='barchart',
            name='description_ht',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='description_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='short_title_ht',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='short_title_ko',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='short_title_ur',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='short_title_zh_hant',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='suffix_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='suffix_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='suffix_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='suffix_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='x_axis_title_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='x_axis_title_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='x_axis_title_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='x_axis_title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='y_axis_title_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='y_axis_title_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='y_axis_title_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='y_axis_title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='title_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='title_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='title_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='tooltip_content_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='tooltip_content_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='tooltip_content_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='tooltip_content_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='categories_ht',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='categories_ko',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='categories_ur',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='categories_zh_hant',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='description_ht',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='description_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='short_title_ht',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='short_title_ko',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='short_title_ur',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='short_title_zh_hant',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='suffix_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='suffix_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='suffix_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='suffix_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='x_axis_title_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='x_axis_title_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='x_axis_title_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='x_axis_title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='y_axis_title_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='y_axis_title_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='y_axis_title_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='y_axis_title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchartdataset',
            name='series_name_ht',
            field=models.CharField(help_text="This will be the individual bar's title in the legend. For example: Part-Time", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchartdataset',
            name='series_name_ko',
            field=models.CharField(help_text="This will be the individual bar's title in the legend. For example: Part-Time", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchartdataset',
            name='series_name_ur',
            field=models.CharField(help_text="This will be the individual bar's title in the legend. For example: Part-Time", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchartdataset',
            name='series_name_zh_hant',
            field=models.CharField(help_text="This will be the individual bar's title in the legend. For example: Part-Time", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='categories_ht',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. It should not include the line category For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='categories_ko',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. It should not include the line category For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='categories_ur',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. It should not include the line category For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='categories_zh_hant',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. It should not include the line category For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='description_ht',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='description_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='short_title_ht',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='short_title_ko',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='short_title_ur',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='short_title_zh_hant',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='suffix_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='suffix_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='suffix_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='suffix_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='x_axis_title_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='x_axis_title_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='x_axis_title_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='x_axis_title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='y_axis_title_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='y_axis_title_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='y_axis_title_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='y_axis_title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumndataset',
            name='series_name_ht',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumndataset',
            name='series_name_ko',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumndataset',
            name='series_name_ur',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumndataset',
            name='series_name_zh_hant',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='description_ht',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='description_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='short_title_ht',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='short_title_ko',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='short_title_ur',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='short_title_zh_hant',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='x_axis_title_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='x_axis_title_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='x_axis_title_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='x_axis_title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='y_axis_title_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='y_axis_title_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='y_axis_title_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='y_axis_title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='categories_ht',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='categories_ko',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='categories_ur',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='categories_zh_hant',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='description_ht',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='description_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='short_title_ht',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='short_title_ko',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='short_title_ur',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='short_title_zh_hant',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='suffix_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='suffix_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='suffix_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='suffix_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='x_axis_title_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='x_axis_title_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='x_axis_title_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='x_axis_title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='y_axis_title_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='y_axis_title_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='y_axis_title_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='y_axis_title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchartdataset',
            name='series_name_ht',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchartdataset',
            name='series_name_ko',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchartdataset',
            name='series_name_ur',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchartdataset',
            name='series_name_zh_hant',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='description_ht',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='description_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='short_title_ht',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='short_title_ko',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='short_title_ur',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='short_title_zh_hant',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='suffix_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='suffix_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='suffix_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='suffix_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='x_axis_title_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='x_axis_title_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='x_axis_title_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='x_axis_title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='y_axis_title_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='y_axis_title_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='y_axis_title_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='y_axis_title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mapchart',
            name='description_ht',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mapchart',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mapchart',
            name='description_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mapchart',
            name='description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mapchart',
            name='short_title_ht',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mapchart',
            name='short_title_ko',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mapchart',
            name='short_title_ur',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mapchart',
            name='short_title_zh_hant',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mapchart',
            name='title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mapchart',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mapchart',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mapchart',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='description_ht',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='description_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='short_title_ht',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='short_title_ko',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='short_title_ur',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='short_title_zh_hant',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='x_axis_title_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='x_axis_title_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='x_axis_title_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='x_axis_title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='y_axis_title_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='y_axis_title_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='y_axis_title_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='y_axis_title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='description_ht',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='description_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='short_title_ht',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='short_title_ko',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='short_title_ur',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='short_title_zh_hant',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='suffix_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='suffix_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='suffix_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='suffix_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='x_axis_title_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='x_axis_title_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='x_axis_title_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='x_axis_title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='y_axis_title_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='y_axis_title_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='y_axis_title_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='y_axis_title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
