# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-08 14:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0020_auto_20190408_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='alternate_axis_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='alternate_axis_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='alternate_axis_title_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='alternate_axis_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='alternate_axis_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='alternate_axis_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='alternate_axis_title_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='alternate_axis_title_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='alternate_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='alternate_axis_title_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='alternate_axis_title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='alternate_axis_title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='alternate_axis_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='alternate_axis_title_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='alternate_axis_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='alternate_axis_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='alternate_axis_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='alternate_axis_title_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='alternate_axis_title_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='alternate_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='alternate_axis_title_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='alternate_axis_title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
