# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-25 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_programlink'),
        ('common_metrics', '0008_auto_20190408_1348'),
        ('visualizations', '0022_datastorylinechart_datastorylinechartdataset'),
    ]

    operations = [
        migrations.CreateModel(
            name='LineChart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('title', models.CharField(max_length=255)),
                ('short_title', models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255)),
                ('description', models.TextField()),
                ('x_axis_title', models.CharField(blank=True, max_length=255)),
                ('y_axis_title', models.CharField(blank=True, max_length=255)),
                ('aggregate_by', models.CharField(choices=[('program', 'program'), ('agency', 'agency'), ('subgroup', 'subgroup')], max_length=255)),
                ('hide_tooltips', models.BooleanField(default=False)),
                ('hide_interactive_legend', models.BooleanField(default=False)),
                ('suffix', models.CharField(blank=True, max_length=255)),
                ('agency', models.ManyToManyField(to='programs.Agency')),
                ('metric_category', models.ManyToManyField(blank=True, null=True, to='common_metrics.MetricCategory')),
                ('metric_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_metrics.MetricName')),
                ('metric_subgroup', smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='metric_category', chained_model_field='metric_category', null=True, to='common_metrics.MetricCategorySubGroup')),
            ],
            options={
                'verbose_name_plural': 'line charts',
            },
        ),
    ]
