# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-25 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0023_linechart'),
    ]

    operations = [
        migrations.AddField(
            model_name='linechart',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='description_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='description_ht',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='description_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='short_title_ar',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='short_title_bn',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='short_title_en',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='short_title_es',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='short_title_fr',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='short_title_ht',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='short_title_ko',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='short_title_ru',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='short_title_ur',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='short_title_zh_hant',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='suffix_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='suffix_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='suffix_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='suffix_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='suffix_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='suffix_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='suffix_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='suffix_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='suffix_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='suffix_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='title_en',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='x_axis_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='x_axis_title_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='x_axis_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='x_axis_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='x_axis_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='x_axis_title_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='x_axis_title_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='x_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='x_axis_title_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='x_axis_title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='y_axis_title_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='y_axis_title_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='y_axis_title_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='y_axis_title_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='y_axis_title_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='y_axis_title_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='y_axis_title_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='y_axis_title_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='y_axis_title_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='y_axis_title_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
