# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-08 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0024_auto_20190425_1849'),
    ]

    operations = [
        migrations.AddField(
            model_name='barchart',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='short_title_pl',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='suffix_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='x_axis_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='barchart',
            name='y_axis_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='coordinate',
            name='tooltip_content_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='categories_pl',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='short_title_pl',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='suffix_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='x_axis_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='y_axis_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchartdataset',
            name='series_name_pl',
            field=models.CharField(help_text="This will be the individual bar's title in the legend. For example: Part-Time", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='alternate_axis_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='categories_pl',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. It should not include the line category For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='short_title_pl',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='suffix_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='x_axis_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='y_axis_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumndataset',
            name='series_name_pl',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='categories_pl',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='short_title_pl',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='suffix_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='x_axis_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='y_axis_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorylinechartdataset',
            name='series_name_pl',
            field=models.CharField(help_text="This will be the individual line's title in the legend. For example: Part-Time", max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='short_title_pl',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='x_axis_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='y_axis_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='categories_pl',
            field=models.TextField(blank=True, help_text='This should be a comma separated set of strings. For example: Under 16,16 to 19,20 to 24,25 to 54', null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='short_title_pl',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='suffix_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='x_axis_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='y_axis_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchartdataset',
            name='series_name_pl',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='alternate_axis_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='short_title_pl',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='suffix_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='x_axis_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='y_axis_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='short_title_pl',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='suffix_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='x_axis_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='linechart',
            name='y_axis_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mapchart',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mapchart',
            name='short_title_pl',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mapchart',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='short_title_pl',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='x_axis_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='sankey',
            name='y_axis_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='short_title_pl',
            field=models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='suffix_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='x_axis_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='y_axis_title_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
