# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-29 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0025_auto_20190508_1608'),
    ]

    operations = [
        migrations.CreateModel(
            name='ShapeFileCoordinate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('hckey', models.CharField(blank=True, max_length=255)),
                ('value', models.CharField(blank=True, max_length=255)),
                ('title', models.CharField(blank=True, max_length=255)),
                ('title_en', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('title_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('title_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('title_es', models.CharField(blank=True, max_length=255, null=True)),
                ('title_pl', models.CharField(blank=True, max_length=255, null=True)),
                ('title_zh_hant', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ht', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ko', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('title_ur', models.CharField(blank=True, max_length=255, null=True)),
                ('tooltip_content', models.CharField(blank=True, max_length=255)),
                ('tooltip_content_en', models.CharField(blank=True, max_length=255, null=True)),
                ('tooltip_content_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('tooltip_content_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('tooltip_content_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('tooltip_content_es', models.CharField(blank=True, max_length=255, null=True)),
                ('tooltip_content_pl', models.CharField(blank=True, max_length=255, null=True)),
                ('tooltip_content_zh_hant', models.CharField(blank=True, max_length=255, null=True)),
                ('tooltip_content_ht', models.CharField(blank=True, max_length=255, null=True)),
                ('tooltip_content_ko', models.CharField(blank=True, max_length=255, null=True)),
                ('tooltip_content_ru', models.CharField(blank=True, max_length=255, null=True)),
                ('tooltip_content_ur', models.CharField(blank=True, max_length=255, null=True)),
                ('map_chart', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizations.MapChart')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
