# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-29 09:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0026_shapefilecoordinate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shapefilecoordinate',
            name='value',
        ),
        migrations.AlterField(
            model_name='shapefilecoordinate',
            name='hckey',
            field=models.CharField(blank=True, max_length=255, verbose_name='HC-Key'),
        ),
    ]
