# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-13 15:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0029_auto_20190529_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapchart',
            name='use_default_map',
            field=models.BooleanField(default=False),
        ),
    ]
