# Generated by Django 2.2 on 2021-02-02 14:47

from django.db import migrations
import django.db.models.deletion
import filer.fields.file


class Migration(migrations.Migration):

    dependencies = [
        ('filer', '0011_auto_20190418_0137'),
        ('visualizations', '0030_mapchart_use_default_map'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapchart',
            name='shapefile_file',
            field=filer.fields.file.FilerFileField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='filer.File'),
        ),
    ]
