# Generated by Django 2.2 on 2021-02-25 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0031_mapchart_shapefile_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='mapchart',
            name='table_column_name',
            field=models.CharField(default='value', help_text='The column name that will appear in the table view', max_length=255),
        ),
    ]
