# Generated by Django 2.2 on 2021-08-25 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0032_mapchart_table_column_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastorybarchart',
            name='decimal_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='is_year',
            field=models.BooleanField(default=1),
        ),
    ]
