# Generated by Django 2.2 on 2021-08-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0033_auto_20210825_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='barchart',
            name='decimal_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='barchart',
            name='is_year',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='decimal_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='is_year',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='decimal_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='is_year',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='decimal_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='is_year',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='decimal_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='is_year',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='decimal_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dualaxislineandcolumn',
            name='is_year',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='linechart',
            name='decimal_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='linechart',
            name='is_year',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='sankey',
            name='decimal_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sankey',
            name='is_year',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='decimal_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='stackedbarchart',
            name='is_year',
            field=models.BooleanField(default=1),
        ),
    ]
