# Generated by Django 2.2 on 2021-09-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0034_auto_20210826_1256'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datastorylinechart',
            options={'verbose_name_plural': 'data stories line charts'},
        ),
        migrations.AlterField(
            model_name='barchart',
            name='decimal_points',
            field=models.IntegerField(default=0, help_text='The number of decimal points to be displayed on datapoints. This truncates rather than rounds. If set at 2 the value 20 will display as 20.00, the value 20.666 will display as 20.66, the value 20.6 will display as 20.60'),
        ),
        migrations.AlterField(
            model_name='barchart',
            name='is_year',
            field=models.BooleanField(default=1, help_text='Controls the formatting of axis numbers. If checked axis numbers will not have commas.'),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='decimal_points',
            field=models.IntegerField(default=0, help_text='The number of decimal points to be displayed on datapoints. This truncates rather than rounds. If set at 2 the value 20 will display as 20.00, the value 20.666 will display as 20.66, the value 20.6 will display as 20.60'),
        ),
        migrations.AlterField(
            model_name='datastorybarchart',
            name='is_year',
            field=models.BooleanField(default=1, help_text='Controls the formatting of axis numbers. If checked axis numbers will not have commas.'),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='decimal_points',
            field=models.IntegerField(default=0, help_text='The number of decimal points to be displayed on datapoints. This truncates rather than rounds. If set at 2 the value 20 will display as 20.00, the value 20.666 will display as 20.66, the value 20.6 will display as 20.60'),
        ),
        migrations.AlterField(
            model_name='datastorydualaxislineandcolumn',
            name='is_year',
            field=models.BooleanField(default=1, help_text='Controls the formatting of axis numbers. If checked axis numbers will not have commas.'),
        ),
        migrations.AlterField(
            model_name='datastorylinechart',
            name='decimal_points',
            field=models.IntegerField(default=0, help_text='The number of decimal points to be displayed on datapoints. This truncates rather than rounds. If set at 2 the value 20 will display as 20.00, the value 20.666 will display as 20.66, the value 20.6 will display as 20.60'),
        ),
        migrations.AlterField(
            model_name='datastorylinechart',
            name='is_year',
            field=models.BooleanField(default=1, help_text='Controls the formatting of axis numbers. If checked axis numbers will not have commas.'),
        ),
        migrations.AlterField(
            model_name='datastorysankey',
            name='decimal_points',
            field=models.IntegerField(default=0, help_text='The number of decimal points to be displayed on datapoints. This truncates rather than rounds. If set at 2 the value 20 will display as 20.00, the value 20.666 will display as 20.66, the value 20.6 will display as 20.60'),
        ),
        migrations.AlterField(
            model_name='datastorysankey',
            name='is_year',
            field=models.BooleanField(default=1, help_text='Controls the formatting of axis numbers. If checked axis numbers will not have commas.'),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='decimal_points',
            field=models.IntegerField(default=0, help_text='The number of decimal points to be displayed on datapoints. This truncates rather than rounds. If set at 2 the value 20 will display as 20.00, the value 20.666 will display as 20.66, the value 20.6 will display as 20.60'),
        ),
        migrations.AlterField(
            model_name='datastorystackedbarchart',
            name='is_year',
            field=models.BooleanField(default=1, help_text='Controls the formatting of axis numbers. If checked axis numbers will not have commas.'),
        ),
        migrations.AlterField(
            model_name='dualaxislineandcolumn',
            name='decimal_points',
            field=models.IntegerField(default=0, help_text='The number of decimal points to be displayed on datapoints. This truncates rather than rounds. If set at 2 the value 20 will display as 20.00, the value 20.666 will display as 20.66, the value 20.6 will display as 20.60'),
        ),
        migrations.AlterField(
            model_name='dualaxislineandcolumn',
            name='is_year',
            field=models.BooleanField(default=1, help_text='Controls the formatting of axis numbers. If checked axis numbers will not have commas.'),
        ),
        migrations.AlterField(
            model_name='linechart',
            name='decimal_points',
            field=models.IntegerField(default=0, help_text='The number of decimal points to be displayed on datapoints. This truncates rather than rounds. If set at 2 the value 20 will display as 20.00, the value 20.666 will display as 20.66, the value 20.6 will display as 20.60'),
        ),
        migrations.AlterField(
            model_name='linechart',
            name='is_year',
            field=models.BooleanField(default=1, help_text='Controls the formatting of axis numbers. If checked axis numbers will not have commas.'),
        ),
        migrations.AlterField(
            model_name='sankey',
            name='decimal_points',
            field=models.IntegerField(default=0, help_text='The number of decimal points to be displayed on datapoints. This truncates rather than rounds. If set at 2 the value 20 will display as 20.00, the value 20.666 will display as 20.66, the value 20.6 will display as 20.60'),
        ),
        migrations.AlterField(
            model_name='sankey',
            name='is_year',
            field=models.BooleanField(default=1, help_text='Controls the formatting of axis numbers. If checked axis numbers will not have commas.'),
        ),
        migrations.AlterField(
            model_name='stackedbarchart',
            name='decimal_points',
            field=models.IntegerField(default=0, help_text='The number of decimal points to be displayed on datapoints. This truncates rather than rounds. If set at 2 the value 20 will display as 20.00, the value 20.666 will display as 20.66, the value 20.6 will display as 20.60'),
        ),
        migrations.AlterField(
            model_name='stackedbarchart',
            name='is_year',
            field=models.BooleanField(default=1, help_text='Controls the formatting of axis numbers. If checked axis numbers will not have commas.'),
        ),
    ]
