# Generated by Django 2.2 on 2022-12-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0037_auto_20221129_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastorybarchart',
            name='data_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='data_notes_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='data_notes_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='data_notes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='data_notes_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='data_notes_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='data_notes_ht',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='data_notes_ko',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='data_notes_pl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='data_notes_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='data_notes_ur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='data_notes_zh_hant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='data_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='data_notes_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='data_notes_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='data_notes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='data_notes_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='data_notes_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='data_notes_ht',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='data_notes_ko',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='data_notes_pl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='data_notes_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='data_notes_ur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='data_notes_zh_hant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='data_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='data_notes_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='data_notes_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='data_notes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='data_notes_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='data_notes_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='data_notes_ht',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='data_notes_ko',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='data_notes_pl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='data_notes_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='data_notes_ur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='data_notes_zh_hant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='data_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='data_notes_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='data_notes_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='data_notes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='data_notes_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='data_notes_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='data_notes_ht',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='data_notes_ko',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='data_notes_pl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='data_notes_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='data_notes_ur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='data_notes_zh_hant',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='data_notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='data_notes_ar',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='data_notes_bn',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='data_notes_en',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='data_notes_es',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='data_notes_fr',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='data_notes_ht',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='data_notes_ko',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='data_notes_pl',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='data_notes_ru',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='data_notes_ur',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='data_notes_zh_hant',
            field=models.TextField(blank=True, null=True),
        ),
    ]
