# Generated by Django 2.2 on 2023-07-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0043_datastoryboxplotdataset_series_outliers'),
    ]

    operations = [
        migrations.AddField(
            model_name='boxplot',
            name='color_by_category',
            field=models.BooleanField(default=False, help_text='Alternate color of boxplots by category. By default, colors will only alternate by series (when multiple boxplots are displayed per category).'),
        ),
        migrations.AddField(
            model_name='datastoryboxplot',
            name='color_by_category',
            field=models.BooleanField(default=False, help_text='Alternate color of boxplots by category. By default, colors will only alternate by series (when multiple boxplots are displayed per category).'),
        ),
    ]
