# Generated by Django 2.2 on 2023-08-04 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0044_auto_20230727_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastoryscatterchart',
            name='x_axis_tick_interval',
            field=models.SmallIntegerField(blank=True, help_text='Optionally, override the default interval with which ticks are shown on the X axis.', null=True),
        ),
        migrations.AddField(
            model_name='scatterchart',
            name='x_axis_tick_interval',
            field=models.SmallIntegerField(blank=True, help_text='Optionally, override the default interval with which ticks are shown on the X axis.', null=True),
        ),
    ]
