# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 10:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('common_metrics', '0001_initial'),
        ('data_stories', '0001_initial'),
        ('visualizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmetricvisualization',
            name='bar_chart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizations.BarChart'),
        ),
        migrations.AddField(
            model_name='commonmetricvisualization',
            name='common_metric',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='common_metrics.CommonMetric'),
        ),
        migrations.AddField(
            model_name='commonmetricvisualization',
            name='dual_axis_line_and_column',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizations.DualAxisLineAndColumn'),
        ),
        migrations.AddField(
            model_name='commonmetricvisualization',
            name='map_chart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizations.MapChart'),
        ),
        migrations.AddField(
            model_name='commonmetricvisualization',
            name='sankey',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizations.Sankey'),
        ),
        migrations.AddField(
            model_name='commonmetricvisualization',
            name='stacked_bar_chart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizations.StackedBarChart'),
        ),
        migrations.AddField(
            model_name='commonmetric',
            name='data_story',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='metric_story', to='data_stories.DataStory'),
        ),
        migrations.AddField(
            model_name='commonmetric',
            name='metric_name',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='common_metrics.MetricName'),
        ),
    ]
