# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 16:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_metrics', '0002_auto_20190220_1021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricfact',
            name='interval_type_ar',
        ),
        migrations.RemoveField(
            model_name='metricfact',
            name='interval_type_bn',
        ),
        migrations.RemoveField(
            model_name='metricfact',
            name='interval_type_en',
        ),
        migrations.RemoveField(
            model_name='metricfact',
            name='interval_type_es',
        ),
        migrations.RemoveField(
            model_name='metricfact',
            name='interval_type_fr',
        ),
        migrations.RemoveField(
            model_name='metricfact',
            name='metric_name_ar',
        ),
        migrations.RemoveField(
            model_name='metricfact',
            name='metric_name_bn',
        ),
        migrations.RemoveField(
            model_name='metricfact',
            name='metric_name_en',
        ),
        migrations.RemoveField(
            model_name='metricfact',
            name='metric_name_es',
        ),
        migrations.RemoveField(
            model_name='metricfact',
            name='metric_name_fr',
        ),
    ]
