# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 16:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_metrics', '0003_auto_20190220_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='metricname',
            name='display_name_ar',
        ),
        migrations.RemoveField(
            model_name='metricname',
            name='display_name_bn',
        ),
        migrations.RemoveField(
            model_name='metricname',
            name='display_name_en',
        ),
        migrations.RemoveField(
            model_name='metricname',
            name='display_name_es',
        ),
        migrations.RemoveField(
            model_name='metricname',
            name='display_name_fr',
        ),
        migrations.RemoveField(
            model_name='metricname',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='metricname',
            name='name_bn',
        ),
        migrations.RemoveField(
            model_name='metricname',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='metricname',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='metricname',
            name='name_fr',
        ),
    ]
