# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_metrics', '0005_auto_20190221_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmetric',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='commonmetric',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metriccategory',
            name='display_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metriccategorysubgroup',
            name='display_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metriccategorysubgroup',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metricname',
            name='display_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
