# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-29 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_metrics', '0006_auto_20190301_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmetric',
            name='metric_total',
            field=models.CharField(default=10, max_length=10),
            preserve_default=False,
        ),
    ]
