# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-08 13:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_metrics', '0007_commonmetric_metric_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmetric',
            name='description_ht',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='commonmetric',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='commonmetric',
            name='description_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='commonmetric',
            name='description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='commonmetric',
            name='title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commonmetric',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commonmetric',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commonmetric',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metriccategory',
            name='display_name_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metriccategory',
            name='display_name_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metriccategory',
            name='display_name_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metriccategory',
            name='display_name_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metriccategorysubgroup',
            name='display_name_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metriccategorysubgroup',
            name='display_name_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metriccategorysubgroup',
            name='display_name_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metriccategorysubgroup',
            name='display_name_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metriccategorysubgroup',
            name='name_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metriccategorysubgroup',
            name='name_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metriccategorysubgroup',
            name='name_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metriccategorysubgroup',
            name='name_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metricname',
            name='display_name_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metricname',
            name='display_name_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metricname',
            name='display_name_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metricname',
            name='display_name_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
