# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-25 18:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0023_linechart'),
        ('common_metrics', '0008_auto_20190408_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmetricvisualization',
            name='line_chart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizations.LineChart'),
        ),
    ]
