# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-08 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_metrics', '0009_commonmetricvisualization_line_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmetric',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='commonmetric',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metriccategory',
            name='display_name_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metriccategorysubgroup',
            name='display_name_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metriccategorysubgroup',
            name='name_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='metricname',
            name='display_name_pl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
