# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-09-10 13:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_metrics', '0010_auto_20190508_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='metriccategorysubgroup',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='metriccategorysubgroup',
            name='order',
            field=models.PositiveSmallIntegerField(default=0, help_text='1 appears before 2', verbose_name='Order'),
        ),
    ]
