# Generated by Django 2.2 on 2021-01-20 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_metrics', '0014_migrate_translatable_fields'),
    ]

    operations = [
      migrations.RemoveField(
        model_name='commonmetric',
        name='description',
      ),
      migrations.RemoveField(
        model_name='commonmetric',
        name='title',
      ),
        migrations.RenameField(
            model_name='commonmetrictranslation',
            old_name='tdescription',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='commonmetrictranslation',
            old_name='ttitle',
            new_name='title',
        ),
    ]
