# Generated by Django 2.2 on 2021-01-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_metrics', '0015_auto_20210120_2347'),
        ('common_metrics', '0012_commonmetricsmarquee'),
    ]

    operations = [
    ]
