# Generated by Django 2.2 on 2021-02-23 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common_metrics', '0017_auto_20210210_2148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonmetric',
            name='internal_status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='D', help_text='Draft hides it from unauthenticated users.', max_length=1, verbose_name='Internal Status'),
        ),
        migrations.AlterField(
            model_name='commonmetric',
            name='public_status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='D', help_text='Draft hides it from unauthenticated users.', max_length=1, verbose_name='Public Status'),
        ),
    ]
