# Generated by Django 2.2 on 2021-06-30 04:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('common_metrics', '0018_auto_20210223_1629'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmetrictranslation',
            name='distribution_view_tooltip',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
