# Generated by Django 2.2 on 2023-07-05 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0039_datastoryscatterchart_datastoryscatterchartdataset_scatterchart'),
        ('common_metrics', '0022_auto_20221129_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmetricvisualization',
            name='scatter_chart',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizations.ScatterChart'),
        ),
    ]
