# Generated by Django 2.2 on 2023-07-13 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0041_auto_20230713_1010'),
        ('common_metrics', '0023_commonmetricvisualization_scatter_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmetricvisualization',
            name='boxplot',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='visualizations.Boxplot'),
        ),
    ]
