# Generated by Django 2.2 on 2023-07-13 11:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common_metrics', '0024_commonmetricvisualization_boxplot'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='commonmetricvisualization',
            name='boxplot',
        ),
        migrations.RemoveField(
            model_name='commonmetricvisualization',
            name='scatter_chart',
        ),
    ]
