# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 10:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion
import tinymce.models
from parler.models import TranslatableModel

class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgencyItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='1 appears before 2', verbose_name='Order')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('title_bn', models.CharField(max_length=255, null=True)),
                ('title_fr', models.CharField(max_length=255, null=True)),
                ('title_es', models.CharField(max_length=255, null=True)),
                ('description', models.TextField()),
                ('description_en', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_bn', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('link_title', models.CharField(max_length=255)),
                ('link_title_en', models.CharField(max_length=255, null=True)),
                ('link_title_ar', models.CharField(max_length=255, null=True)),
                ('link_title_bn', models.CharField(max_length=255, null=True)),
                ('link_title_fr', models.CharField(max_length=255, null=True)),
                ('link_title_es', models.CharField(max_length=255, null=True)),
                ('link_text', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BasicPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('expire_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Expiration Date')),
                ('pub_date', models.DateField(db_index=True, default=datetime.date.today, help_text='Date to be published', verbose_name='Published Date')),
                ('status', models.CharField(choices=[('H', 'Hidden'), ('D', 'Draft'), ('P', 'Published')], default='D', help_text='Hidden is publicly available, but not a part of the nav or lists. Draft hides it from unauthenticated users.', max_length=1, verbose_name='Status')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('title_bn', models.CharField(max_length=255, null=True)),
                ('title_fr', models.CharField(max_length=255, null=True)),
                ('title_es', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('top_wysiwyg', tinymce.models.HTMLField(blank=True, null=True)),
                ('bottom_wysiwyg', tinymce.models.HTMLField(blank=True, null=True)),
                ('agencies', models.ManyToManyField(blank=True, to='page.AgencyItem')),
            ],
            options={
                'abstract': False,
            },
            bases=(TranslatableModel, models.Model),
        ),
        migrations.CreateModel(
            name='FooterNavigationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='1 appears before 2', verbose_name='Order')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('title_bn', models.CharField(max_length=255, null=True)),
                ('title_fr', models.CharField(max_length=255, null=True)),
                ('title_es', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, help_text='must match intended page path', max_length=255, null=True)),
                ('basic_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.BasicPage')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('expire_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Expiration Date')),
                ('pub_date', models.DateField(db_index=True, default=datetime.date.today, help_text='Date to be published', verbose_name='Published Date')),
                ('status', models.CharField(choices=[('H', 'Hidden'), ('D', 'Draft'), ('P', 'Published')], default='D', help_text='Hidden is publicly available, but not a part of the nav or lists. Draft hides it from unauthenticated users.', max_length=1, verbose_name='Status')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('title_bn', models.CharField(max_length=255, null=True)),
                ('title_fr', models.CharField(max_length=255, null=True)),
                ('title_es', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MainNavigationItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='1 appears before 2', verbose_name='Order')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('title_bn', models.CharField(max_length=255, null=True)),
                ('title_fr', models.CharField(max_length=255, null=True)),
                ('title_es', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(blank=True, help_text='must match intended page path', max_length=255, null=True)),
                ('hover_description', models.TextField()),
                ('hover_description_en', models.TextField(null=True)),
                ('hover_description_ar', models.TextField(null=True)),
                ('hover_description_bn', models.TextField(null=True)),
                ('hover_description_fr', models.TextField(null=True)),
                ('hover_description_es', models.TextField(null=True)),
                ('basic_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.BasicPage')),
                ('landing_page', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.LandingPage')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProgramLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='1 appears before 2', verbose_name='Order')),
                ('link_title', models.CharField(max_length=255)),
                ('link_title_en', models.CharField(max_length=255, null=True)),
                ('link_title_ar', models.CharField(max_length=255, null=True)),
                ('link_title_bn', models.CharField(max_length=255, null=True)),
                ('link_title_fr', models.CharField(max_length=255, null=True)),
                ('link_title_es', models.CharField(max_length=255, null=True)),
                ('link_url', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='footernavigationitem',
            name='landing_page',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='page.LandingPage'),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='program_links',
            field=models.ManyToManyField(blank=True, to='page.ProgramLink'),
        ),
    ]
