# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 15:01
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('page', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='agencyitem',
            old_name='link_text',
            new_name='link_url',
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='image',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.FILER_IMAGE_MODEL),
        ),
    ]
