# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0002_auto_20190220_1501'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyitem',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='link_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footernavigationitem',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='hover_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programlink',
            name='link_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
