# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-05 13:04
from __future__ import unicode_literals

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0003_auto_20190301_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='basicpage',
            name='bottom_wysiwyg_ar',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='bottom_wysiwyg_bn',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='bottom_wysiwyg_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='bottom_wysiwyg_es',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='bottom_wysiwyg_fr',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='bottom_wysiwyg_ru',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='top_wysiwyg_ar',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='top_wysiwyg_bn',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='top_wysiwyg_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='top_wysiwyg_es',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='top_wysiwyg_fr',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='top_wysiwyg_ru',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
