# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0005_auto_20190313_1541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicpage',
            name='program_links',
        ),
        migrations.DeleteModel(
            name='ProgramLink',
        ),
    ]
