# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-03 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0007_auto_20190403_1152'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description_ru',
            field=models.TextField(null=True),
        ),
    ]
