# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-08 13:48
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0008_auto_20190403_1740'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyitem',
            name='description_ht',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='description_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='link_title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='link_title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='link_title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='link_title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='bottom_wysiwyg_ht',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='bottom_wysiwyg_ko',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='bottom_wysiwyg_ur',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='bottom_wysiwyg_zh_hant',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='top_wysiwyg_ht',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='top_wysiwyg_ko',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='top_wysiwyg_ur',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='top_wysiwyg_zh_hant',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footernavigationitem',
            name='title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footernavigationitem',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footernavigationitem',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footernavigationitem',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description_ht',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='hover_description_ht',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='hover_description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='hover_description_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='hover_description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
