# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-08 16:08
from __future__ import unicode_literals

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0009_auto_20190408_1348'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyitem',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='link_title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='bottom_wysiwyg_pl',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='basicpage',
            name='top_wysiwyg_pl',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='footernavigationitem',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='hover_description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
