# Generated by Django 2.2 on 2021-01-05 04:44

from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0010_auto_20190508_1608'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicpage',
            name='bottom_wysiwyg_ar',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='bottom_wysiwyg_bn',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='bottom_wysiwyg_en',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='bottom_wysiwyg_es',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='bottom_wysiwyg_fr',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='bottom_wysiwyg_ht',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='bottom_wysiwyg_ko',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='bottom_wysiwyg_pl',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='bottom_wysiwyg_ru',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='bottom_wysiwyg_ur',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='bottom_wysiwyg_zh_hant',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='title_bn',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='title_ht',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='title_ko',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='title_pl',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='title_ur',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='title_zh_hant',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='top_wysiwyg_ar',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='top_wysiwyg_bn',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='top_wysiwyg_en',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='top_wysiwyg_es',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='top_wysiwyg_fr',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='top_wysiwyg_ht',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='top_wysiwyg_ko',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='top_wysiwyg_pl',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='top_wysiwyg_ru',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='top_wysiwyg_ur',
        ),
        migrations.RemoveField(
            model_name='basicpage',
            name='top_wysiwyg_zh_hant',
        ),
        migrations.CreateModel(
            name='BasicPageTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('_t_title', models.CharField(max_length=255)),
                ('_t_top_wysiwyg', tinymce.models.HTMLField(blank=True, null=True)),
                ('_t_bottom_wysiwyg', tinymce.models.HTMLField(blank=True, null=True)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page.BasicPage')),
            ],
            options={
                'verbose_name': 'basic page Translation',
                'db_table': 'page_basicpage_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
