# Generated by Django 2.2 on 2021-01-05 04:44

from django.db import migrations
from django.conf import settings
from django.core.exceptions import ObjectDoesNotExist


def forwards_func(apps, schema_editor):
    BasicPage = apps.get_model('page', 'BasicPage')
    BasicPageTranslation = apps.get_model('page', 'BasicPageTranslation')
    for object in BasicPage.objects.all():
        BasicPageTranslation.objects.create(
            master_id=object.pk,
            language_code=settings.LANGUAGE_CODE,
            _t_title=object.title,
            _t_top_wysiwyg=object.top_wysiwyg,
            _t_bottom_wysiwyg=object.bottom_wysiwyg,
        )


def backwards_func(apps, schema_editor):
    BasicPage = apps.get_model('page', 'BasicPage')
    BasicPageTranslation = apps.get_model('page', 'BasicPageTranslation')
    for object in BasicPage.objects.all():
        translation = _get_translation(object, BasicPageTranslation)
        object.title = translation._t_title
        object.top_wysiwyg = translation._t_top_wysiwyg
        object.bottom_wysiwyg = translation._t_bottom_wysiwyg
        object.save()  # Note this only calls Model.save()


def _get_translation(object, BasicPageTranslation):
    translations = BasicPageTranslation.objects.filter(master_id=object.pk)
    try:
        # Try default translation
        return translations.get(language_code=settings.LANGUAGE_CODE)
    except ObjectDoesNotExist:
        try:
            # Try default language
            return translations.get(language_code=settings.PARLER_DEFAULT_LANGUAGE_CODE)
        except ObjectDoesNotExist:
            # Maybe the object was translated only in a specific language?
            # Hope there is a single translation
            return translations.get()


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0011_auto_20210105_0444'),
    ]

    operations = [
        migrations.RunPython(forwards_func, backwards_func),
    ]
