# Generated by Django 2.2 on 2021-01-05 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0013_auto_20210105_0448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basicpagetranslation',
            old_name='_t_bottom_wysiwyg',
            new_name='bottom_wysiwyg',
        ),
        migrations.RenameField(
            model_name='basicpagetranslation',
            old_name='_t_title',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='basicpagetranslation',
            old_name='_t_top_wysiwyg',
            new_name='top_wysiwyg',
        ),
    ]
