# Generated by Django 2.2 on 2021-01-20 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0015_migrate_top_bottom_wysiwyg_to_plugins'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basicpagetranslation',
            name='bottom_wysiwyg',
        ),
        migrations.RemoveField(
            model_name='basicpagetranslation',
            name='top_wysiwyg',
        ),
    ]
