# Generated by Django 2.2 on 2021-02-23 17:44

import apps.page.models
from django.db import migrations, models
import django.db.models.deletion
import parler.fields
import parler.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0017_auto_20210210_2148'),
    ]

    operations = [
        migrations.CreateModel(
            name='Footer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
            bases=(parler.models.TranslatableModelMixin, models.Model),
        ),
        migrations.RemoveField(
            model_name='footernavigationitem',
            name='basic_page',
        ),
        migrations.RemoveField(
            model_name='footernavigationitem',
            name='landing_page',
        ),
        migrations.AddField(
            model_name='footernavigationitem',
            name='column',
            field=models.CharField(blank=True, choices=[('S', 'Second'), ('T', 'Third')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='footernavigationitem',
            name='external',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='footernavigationitem',
            name='url',
            field=models.CharField(max_length=200, null=True, validators=[apps.page.models.OptionalSchemeURLValidator()]),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='internal_status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='D', help_text='Draft hides it from unauthenticated users.', max_length=1, verbose_name='Internal Status'),
        ),
        migrations.AlterField(
            model_name='basicpage',
            name='public_status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='D', help_text='Draft hides it from unauthenticated users.', max_length=1, verbose_name='Public Status'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='internal_status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='D', help_text='Draft hides it from unauthenticated users.', max_length=1, verbose_name='Internal Status'),
        ),
        migrations.AlterField(
            model_name='landingpage',
            name='public_status',
            field=models.CharField(choices=[('D', 'Draft'), ('P', 'Published')], default='D', help_text='Draft hides it from unauthenticated users.', max_length=1, verbose_name='Public Status'),
        ),
        migrations.CreateModel(
            name='FooterTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language_code', models.CharField(db_index=True, max_length=15, verbose_name='Language')),
                ('title', models.CharField(max_length=255)),
                ('master', parler.fields.TranslationsForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='translations', to='page.Footer')),
            ],
            options={
                'verbose_name': 'footer Translation',
                'db_table': 'page_footer_translation',
                'db_tablespace': '',
                'managed': True,
                'default_permissions': (),
                'unique_together': {('language_code', 'master')},
            },
            bases=(parler.models.TranslatedFieldsModelMixin, models.Model),
        ),
    ]
