# Generated by Django 2.2 on 2021-04-29 13:36

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0018_auto_20210223_1744'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='homepage_description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
