# Generated by Django 2.2 on 2021-04-29 13:40

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0019_landingpage_homepage_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='homepage_description_ar',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='homepage_description_bn',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='homepage_description_en',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='homepage_description_es',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='homepage_description_fr',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='homepage_description_ht',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='homepage_description_ko',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='homepage_description_pl',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='homepage_description_ru',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='homepage_description_ur',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='homepage_description_zh_hant',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
