# Generated by Django 2.2 on 2022-11-29 15:00

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('page', '0021_auto_20220322_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='agencyitem',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='description_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='description_ht',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='description_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='link_title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='link_title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='link_title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='link_title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='link_title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='link_title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='link_title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='link_title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='link_title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='link_title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agencyitem',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footernavigationitem',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footernavigationitem',
            name='title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footernavigationitem',
            name='title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footernavigationitem',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footernavigationitem',
            name='title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footernavigationitem',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footernavigationitem',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footernavigationitem',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footernavigationitem',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='footernavigationitem',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description_ar',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description_bn',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description_es',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description_fr',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description_ht',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description_ko',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description_pl',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description_ru',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description_ur',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='description_zh_hant',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='homepage_description_ar',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='homepage_description_bn',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='homepage_description_es',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='homepage_description_fr',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='homepage_description_ht',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='homepage_description_ko',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='homepage_description_pl',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='homepage_description_ru',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='homepage_description_ur',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='homepage_description_zh_hant',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='landingpage',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='hover_description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='hover_description_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='hover_description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='hover_description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='hover_description_ht',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='hover_description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='hover_description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='hover_description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='hover_description_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='hover_description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='title_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='title_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='title_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='title_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='title_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='title_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='title_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='title_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='mainnavigationitem',
            name='title_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
