# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-22 04:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fluent_contents', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='WysiwygBlockItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('content', tinymce.models.HTMLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'WYSIWYG block',
                'verbose_name_plural': 'WYSIWYG blocks',
                'db_table': 'contentitem_plugins_wysiwygblockitem',
                'manager_inheritance_from_future': True,
            },
            bases=('fluent_contents.contentitem',),
        ),
    ]
