# Generated by Django 2.2 on 2020-12-29 21:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluent_contents', '0001_initial'),
        ('visualizations', '0030_mapchart_use_default_map'),
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StackedBarChartBlockItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('stacked_bar_chart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visualizations.StackedBarChart')),
            ],
            options={
                'verbose_name': 'Stacked Bar Chart',
                'verbose_name_plural': 'Stacked Bar Charts',
                'db_table': 'contentitem_plugins_stackedbarchartblockitem',
            },
            bases=('fluent_contents.contentitem',),
        ),
        migrations.CreateModel(
            name='SankeyBlockItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('sankey', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visualizations.Sankey')),
            ],
            options={
                'verbose_name': 'Sankey',
                'verbose_name_plural': 'Sankeys',
                'db_table': 'contentitem_plugins_sankeyblockitem',
            },
            bases=('fluent_contents.contentitem',),
        ),
        migrations.CreateModel(
            name='LineChartBlockItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('line_chart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visualizations.LineChart')),
            ],
            options={
                'verbose_name': 'Line Chart',
                'verbose_name_plural': 'Line Charts',
                'db_table': 'contentitem_plugins_linechartblockitem',
            },
            bases=('fluent_contents.contentitem',),
        ),
        migrations.CreateModel(
            name='DualAxisLineAndColumnBlockItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('dual_axis_line_and_column', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visualizations.DualAxisLineAndColumn')),
            ],
            options={
                'verbose_name': 'Dual Axis Line And Column',
                'verbose_name_plural': 'Dual Axis Line And Columns',
                'db_table': 'contentitem_plugins_dualaxislineandcolumnblockitem',
            },
            bases=('fluent_contents.contentitem',),
        ),
        migrations.CreateModel(
            name='BarChartBlockItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Order')),
                ('bar_chart', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='visualizations.BarChart')),
            ],
            options={
                'verbose_name': 'Bar Chart',
                'verbose_name_plural': 'Bar Charts',
                'db_table': 'contentitem_plugins_barchartblockitem',
            },
            bases=('fluent_contents.contentitem',),
        ),
    ]
