# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-22 04:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('fluent_contents', '0001_initial'),
        ('plugins', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmbedBlockItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('embed_code', models.CharField(max_length=3000)),
            ],
            options={
                'db_table': 'contentitem_plugins_embedblockitem',
                'abstract': False,
            },
            bases=('fluent_contents.contentitem',),
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('base_objects', django.db.models.manager.Manager()),
            ],
        ),
    ]
