# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2020-12-29 22:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.FILER_IMAGE_MODEL),
        ('fluent_contents', '0001_initial'),
        ('plugins', '0002_embedblockitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageBlockItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('image', filer.fields.image.FilerImageField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.FILER_IMAGE_MODEL)),
            ],
            options={
                'verbose_name': 'Image block',
                'verbose_name_plural': 'Image blocks',
                'db_table': 'contentitem_plugins_imageblockitem',
                'manager_inheritance_from_future': True,
            },
            bases=('fluent_contents.contentitem',),
        ),
    ]
