# Generated by Django 2.2 on 2021-01-04 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0003_imageblockitem'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='embedblockitem',
            options={'base_manager_name': 'objects'},
        ),
        migrations.AlterModelManagers(
            name='embedblockitem',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='wysiwygblockitem',
            name='title',
            field=models.CharField(default='', max_length=200, verbose_name='Title'),
            preserve_default=False,
        ),
    ]
