# Generated by Django 2.2 on 2021-01-11 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0002_barchartblockitem_dualaxislineandcolumnblockitem_linechartblockitem_sankeyblockitem_stackedbarchartb'),
        ('plugins', '0004_auto_20210104_2231'),
    ]

    operations = [
    ]
