# Generated by Django 2.2 on 2021-01-20 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0005_merge_20210111_1515'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wysiwygblockitem',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Title'),
        ),
    ]
