# Generated by Django 2.2 on 2021-01-20 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0007_migrate_commonmetricvisualization_to_plugins'),
        ('plugins', '0006_auto_20210120_1654'),
    ]

    operations = [
    ]
