# Generated by Django 2.2 on 2021-01-25 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0008_merge_20210120_2211'),
        ('plugins', '0007_auto_20210121_1026'),
    ]

    operations = [
    ]
