# Generated by Django 2.2 on 2021-01-25 21:34

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluent_contents', '0001_initial'),
        ('plugins', '0009_merge_20210125_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='MapChartBlockItem',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('title', models.CharField(max_length=255)),
                ('short_title', models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255)),
                ('description', models.TextField()),
                ('shapefile', django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True)),
                ('use_default_map', models.BooleanField(default=False)),
                ('hide_tooltips', models.BooleanField(default=False)),
                ('hide_interactive_legend', models.BooleanField(default=False)),
                ('hckey', models.CharField(blank=True, max_length=255, verbose_name='HC-Key')),
                ('shapefile_title', models.CharField(blank=True, max_length=255)),
                ('shapefile_tooltip_content', models.CharField(blank=True, max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9)),
                ('coordinate_title', models.CharField(blank=True, max_length=255)),
                ('coordinate_tooltip_content', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Map Chart',
                'verbose_name_plural': 'Map Charts',
                'db_table': 'contentitem_plugins_mapchartblockitem',
            },
            bases=('fluent_contents.contentitem',),
        ),
    ]
