# Generated by Django 2.2 on 2021-01-26 21:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visualizations', '0030_mapchart_use_default_map'),
        ('fluent_contents', '0001_initial'),
        ('plugins', '0009_merge_20210125_1232'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataStoryStackedBarChart',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('stacked_bar_chart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visualizations.DataStoryStackedBarChart')),
            ],
            options={
                'verbose_name': 'Data Story Stacked Bar Chart',
                'verbose_name_plural': 'Data Story Stacked Bar Charts',
                'db_table': 'contentitem_plugins_datastorystackedbarchart',
            },
            bases=('fluent_contents.contentitem',),
        ),
        migrations.CreateModel(
            name='DataStorySankey',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('sankey', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visualizations.DataStorySankey')),
            ],
            options={
                'verbose_name': 'Data Story Sankey',
                'verbose_name_plural': 'Data Story Sankeys',
                'db_table': 'contentitem_plugins_datastorysankey',
            },
            bases=('fluent_contents.contentitem',),
        ),
        migrations.CreateModel(
            name='DataStoryMapChart',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('map_chart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visualizations.MapChart')),
            ],
            options={
                'verbose_name': 'Data Story Map Chart',
                'verbose_name_plural': 'Data Story Map Charts',
                'db_table': 'contentitem_plugins_datastorymapchart',
            },
            bases=('fluent_contents.contentitem',),
        ),
        migrations.CreateModel(
            name='DataStoryLineChart',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('line_chart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visualizations.DataStoryLineChart')),
            ],
            options={
                'verbose_name': 'Data Story Line Chart',
                'verbose_name_plural': 'Data Story Line Charts',
                'db_table': 'contentitem_plugins_datastorylinechart',
            },
            bases=('fluent_contents.contentitem',),
        ),
        migrations.CreateModel(
            name='DataStoryDualAxisLineAndColumn',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('dual_axis_line_and_column', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visualizations.DataStoryDualAxisLineAndColumn')),
            ],
            options={
                'verbose_name': 'Data Story Dual Axis Line And Column Chart',
                'verbose_name_plural': 'Data Story Dual Axis Line And Column Charts',
                'db_table': 'contentitem_plugins_datastorydualaxislineandcolumn',
            },
            bases=('fluent_contents.contentitem',),
        ),
        migrations.CreateModel(
            name='DataStoryBarChart',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('bar_chart', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visualizations.DataStoryBarChart')),
            ],
            options={
                'verbose_name': 'Data Story Bar Chart',
                'verbose_name_plural': 'Data Story Bar Charts',
                'db_table': 'contentitem_plugins_datastorybarchart',
            },
            bases=('fluent_contents.contentitem',),
        ),
    ]
