# Generated by Django 2.2 on 2021-01-27 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0010_mapchartblockitem'),
        ('plugins', '0011_migrate_datastroyvisualization_to_plugins'),
    ]

    operations = [
    ]
