# Generated by Django 2.2 on 2021-02-23 17:44

import apps.plugins.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fluent_contents', '0001_initial'),
        ('plugins', '0012_merge_20210127_1330'),
    ]

    operations = [
        migrations.CreateModel(
            name='LinkPlugin',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('url', models.CharField(max_length=200, null=True, validators=[apps.plugins.models.OptionalSchemeURLValidator()])),
                ('link_text', models.CharField(max_length=200, null=True)),
                ('external', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'contentitem_plugins_linkplugin',
                'abstract': False,
                'base_manager_name': 'objects',
            },
            bases=('fluent_contents.contentitem',),
        ),
    ]
