# Generated by Django 2.2 on 2021-03-03 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0013_linkplugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmetricbarchart',
            name='chart_tooltip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commonmetricdualaxislineandcolumn',
            name='chart_tooltip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commonmetriclinechart',
            name='chart_tooltip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commonmetricsankey',
            name='chart_tooltip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='commonmetricstackedbarchart',
            name='chart_tooltip',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
