# Generated by Django 2.2 on 2021-06-30 00:41

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0014_auto_20210303_0452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonmetricbarchart',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonmetricdualaxislineandcolumn',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonmetriclinechart',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonmetricsankey',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='commonmetricstackedbarchart',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mapchartblockitem',
            name='description',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
