# Generated by Django 2.2 on 2021-08-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0016_auto_20210630_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmetricbarchart',
            name='decimal_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commonmetricbarchart',
            name='is_year',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='commonmetricdualaxislineandcolumn',
            name='decimal_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commonmetricdualaxislineandcolumn',
            name='is_year',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='commonmetriclinechart',
            name='decimal_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commonmetriclinechart',
            name='is_year',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='commonmetricsankey',
            name='decimal_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commonmetricsankey',
            name='is_year',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='commonmetricstackedbarchart',
            name='decimal_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='commonmetricstackedbarchart',
            name='is_year',
            field=models.BooleanField(default=1),
        ),
    ]
