# Generated by Django 2.2 on 2021-08-19 05:09

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0016_auto_20210630_0441'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmetricbarchart',
            name='data_notes',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonmetricdualaxislineandcolumn',
            name='data_notes',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonmetriclinechart',
            name='data_notes',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonmetricsankey',
            name='data_notes',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='commonmetricstackedbarchart',
            name='data_notes',
            field=tinymce.models.HTMLField(blank=True, null=True),
        ),
    ]
