# Generated by Django 2.2 on 2021-08-25 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0017_auto_20210825_0919'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastorybarchart',
            name='decimal_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datastorybarchart',
            name='is_year',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='decimal_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datastorydualaxislineandcolumn',
            name='is_year',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='decimal_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datastorylinechart',
            name='is_year',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='datastorymapchart',
            name='decimal_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datastorymapchart',
            name='is_year',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='decimal_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datastorysankey',
            name='is_year',
            field=models.BooleanField(default=1),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='decimal_points',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='datastorystackedbarchart',
            name='is_year',
            field=models.BooleanField(default=1),
        ),
    ]
