# Generated by Django 2.2 on 2021-08-25 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0018_auto_20210825_1107'),
        ('plugins', '0017_auto_20210819_0509'),
    ]

    operations = [
    ]
