# Generated by Django 2.2 on 2021-09-28 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0019_merge_2021825_1242'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='datastorybarchart',
            name='decimal_points',
        ),
        migrations.RemoveField(
            model_name='datastorybarchart',
            name='is_year',
        ),
        migrations.RemoveField(
            model_name='datastorydualaxislineandcolumn',
            name='decimal_points',
        ),
        migrations.RemoveField(
            model_name='datastorydualaxislineandcolumn',
            name='is_year',
        ),
        migrations.RemoveField(
            model_name='datastorylinechart',
            name='decimal_points',
        ),
        migrations.RemoveField(
            model_name='datastorylinechart',
            name='is_year',
        ),
        migrations.RemoveField(
            model_name='datastorymapchart',
            name='decimal_points',
        ),
        migrations.RemoveField(
            model_name='datastorymapchart',
            name='is_year',
        ),
        migrations.RemoveField(
            model_name='datastorysankey',
            name='decimal_points',
        ),
        migrations.RemoveField(
            model_name='datastorysankey',
            name='is_year',
        ),
        migrations.RemoveField(
            model_name='datastorystackedbarchart',
            name='decimal_points',
        ),
        migrations.RemoveField(
            model_name='datastorystackedbarchart',
            name='is_year',
        ),
    ]
