# Generated by Django 2.2 on 2021-09-28 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0020_auto_20210928_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonmetricbarchart',
            name='decimal_points',
            field=models.IntegerField(default=0, help_text='The number of decimal points to be displayed on datapoints. This truncates rather than rounds. If set at 2 the value 20 will display as 20.00, the value 20.666 will display as 20.66, the value 20.6 will display as 20.60'),
        ),
        migrations.AlterField(
            model_name='commonmetricbarchart',
            name='is_year',
            field=models.BooleanField(default=1, help_text='Controls the formatting of axis numbers. If checked axis numbers will not have commas.'),
        ),
        migrations.AlterField(
            model_name='commonmetricdualaxislineandcolumn',
            name='decimal_points',
            field=models.IntegerField(default=0, help_text='The number of decimal points to be displayed on datapoints. This truncates rather than rounds. If set at 2 the value 20 will display as 20.00, the value 20.666 will display as 20.66, the value 20.6 will display as 20.60'),
        ),
        migrations.AlterField(
            model_name='commonmetricdualaxislineandcolumn',
            name='is_year',
            field=models.BooleanField(default=1, help_text='Controls the formatting of axis numbers. If checked axis numbers will not have commas.'),
        ),
        migrations.AlterField(
            model_name='commonmetriclinechart',
            name='decimal_points',
            field=models.IntegerField(default=0, help_text='The number of decimal points to be displayed on datapoints. This truncates rather than rounds. If set at 2 the value 20 will display as 20.00, the value 20.666 will display as 20.66, the value 20.6 will display as 20.60'),
        ),
        migrations.AlterField(
            model_name='commonmetriclinechart',
            name='is_year',
            field=models.BooleanField(default=1, help_text='Controls the formatting of axis numbers. If checked axis numbers will not have commas.'),
        ),
        migrations.AlterField(
            model_name='commonmetricsankey',
            name='decimal_points',
            field=models.IntegerField(default=0, help_text='The number of decimal points to be displayed on datapoints. This truncates rather than rounds. If set at 2 the value 20 will display as 20.00, the value 20.666 will display as 20.66, the value 20.6 will display as 20.60'),
        ),
        migrations.AlterField(
            model_name='commonmetricsankey',
            name='is_year',
            field=models.BooleanField(default=1, help_text='Controls the formatting of axis numbers. If checked axis numbers will not have commas.'),
        ),
        migrations.AlterField(
            model_name='commonmetricstackedbarchart',
            name='decimal_points',
            field=models.IntegerField(default=0, help_text='The number of decimal points to be displayed on datapoints. This truncates rather than rounds. If set at 2 the value 20 will display as 20.00, the value 20.666 will display as 20.66, the value 20.6 will display as 20.60'),
        ),
        migrations.AlterField(
            model_name='commonmetricstackedbarchart',
            name='is_year',
            field=models.BooleanField(default=1, help_text='Controls the formatting of axis numbers. If checked axis numbers will not have commas.'),
        ),
    ]
