# Generated by Django 2.2 on 2023-07-05 20:17

from django.db import migrations, models
import django.db.models.deletion
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('fluent_contents', '0001_initial'),
        ('plugins', '0021_auto_20210928_2258'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommonMetricScatterChart',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('title', models.CharField(max_length=255)),
                ('short_title', models.CharField(blank=True, help_text='This title is required for the small card display and for the file name when data is exported', max_length=255)),
                ('description', tinymce.models.HTMLField(blank=True, null=True)),
                ('chart_tooltip', tinymce.models.HTMLField(blank=True, null=True)),
                ('data_notes', tinymce.models.HTMLField(blank=True, null=True)),
                ('x_axis_title', models.CharField(blank=True, max_length=255)),
                ('y_axis_title', models.CharField(blank=True, max_length=255)),
                ('aggregate_by', models.CharField(choices=[('program', 'program'), ('agency', 'agency'), ('subgroup', 'subgroup')], max_length=255)),
                ('decimal_points', models.IntegerField(default=0, help_text='The number of decimal points to be displayed on datapoints. This truncates rather than rounds. If set at 2 the value 20 will display as 20.00, the value 20.666 will display as 20.66, the value 20.6 will display as 20.60')),
                ('is_year', models.BooleanField(default=0, help_text='Controls the formatting of axis numbers. If checked axis numbers will not have commas.')),
                ('hide_tooltips', models.BooleanField(default=False)),
                ('hide_interactive_legend', models.BooleanField(default=False)),
                ('suffix', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'verbose_name': 'Scatter Chart',
                'verbose_name_plural': 'Scatter Charts',
                'db_table': 'contentitem_plugins_commonmetricscatterchart',
            },
            bases=('fluent_contents.contentitem',),
        ),
        migrations.CreateModel(
            name='DataStoryScatterChart',
            fields=[
                ('contentitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fluent_contents.ContentItem')),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Data Story Scatter Chart',
                'verbose_name_plural': 'Data Story Scatter Charts',
                'db_table': 'contentitem_plugins_datastoryscatterchart',
            },
            bases=('fluent_contents.contentitem',),
        ),
    ]
