# Generated by Django 2.2 on 2023-07-05 20:17

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0022_auto_20221129_1500'),
        ('common_metrics', '0023_commonmetricvisualization_scatter_chart'),
        ('plugins', '0022_commonmetricscatterchart_datastoryscatterchart'),
        ('visualizations', '0039_datastoryscatterchart_datastoryscatterchartdataset_scatterchart'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastoryscatterchart',
            name='scatter_chart',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visualizations.DataStoryScatterChart'),
        ),
        migrations.AddField(
            model_name='commonmetricscatterchart',
            name='agency',
            field=models.ManyToManyField(db_table='contentitems_scatterchart_agency', to='programs.Agency'),
        ),
        migrations.AddField(
            model_name='commonmetricscatterchart',
            name='metric_category',
            field=models.ManyToManyField(blank=True, db_table='contentitems_scatterchart_metriccategory', null=True, to='common_metrics.MetricCategory'),
        ),
        migrations.AddField(
            model_name='commonmetricscatterchart',
            name='metric_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_metrics.MetricName'),
        ),
        migrations.AddField(
            model_name='commonmetricscatterchart',
            name='metric_subgroup',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='metric_category', chained_model_field='metric_category', db_table='contentitems_scatterchart_metricsubgroup', null=True, to='common_metrics.MetricCategorySubGroup'),
        ),
    ]
