# Generated by Django 2.2 on 2023-07-12 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0023_auto_20230705_2017'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmetriclinechart',
            name='is_area',
            field=models.BooleanField(default=False, help_text='If checked, will display as an area chart.'),
        ),
    ]
