# Generated by Django 2.2 on 2023-07-13 10:10

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0022_auto_20221129_1500'),
        ('common_metrics', '0024_commonmetricvisualization_boxplot'),
        ('plugins', '0025_auto_20230713_1010'),
        ('visualizations', '0041_auto_20230713_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='datastoryboxplot',
            name='boxplot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visualizations.DataStoryBoxplot'),
        ),
        migrations.AddField(
            model_name='commonmetricboxplot',
            name='agency',
            field=models.ManyToManyField(db_table='contentitems_boxplot_agency', to='programs.Agency'),
        ),
        migrations.AddField(
            model_name='commonmetricboxplot',
            name='metric_category',
            field=models.ManyToManyField(blank=True, db_table='contentitems_boxplot_metriccategory', null=True, to='common_metrics.MetricCategory'),
        ),
        migrations.AddField(
            model_name='commonmetricboxplot',
            name='metric_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='common_metrics.MetricName'),
        ),
        migrations.AddField(
            model_name='commonmetricboxplot',
            name='metric_subgroup',
            field=smart_selects.db_fields.ChainedManyToManyField(blank=True, chained_field='metric_category', chained_model_field='metric_category', db_table='contentitems_boxplot_metricsubgroup', null=True, to='common_metrics.MetricCategorySubGroup'),
        ),
    ]
