# Generated by Django 2.2 on 2023-07-27 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0026_auto_20230713_1010'),
    ]

    operations = [
        migrations.AddField(
            model_name='commonmetricboxplot',
            name='color_by_category',
            field=models.BooleanField(default=False, help_text='Alternate the color of boxplots by category. By default, colors will only alternate by series (when multiple boxplots are displayed per category).'),
        ),
    ]
