# Generated by Django 2.2 on 2023-08-07 12:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plugins', '0028_commonmetricscatterchart_x_axis_tick_interval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commonmetricscatterchart',
            name='x_axis_tick_interval',
            field=models.SmallIntegerField(blank=True, help_text='Optionally, override the default interval with which ticks are shown on the X axis.', null=True, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
