# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-20 10:21
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Agency',
            fields=[
                ('acronym', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, null=True)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ar', models.CharField(max_length=255, null=True)),
                ('name_bn', models.CharField(max_length=255, null=True)),
                ('name_fr', models.CharField(max_length=255, null=True)),
                ('name_es', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='1 appears before 2', verbose_name='Order')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('name_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('name_es', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.CharField(blank=True, max_length=255)),
                ('phone', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Program',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('expire_date', models.DateField(blank=True, db_index=True, null=True, verbose_name='Expiration Date')),
                ('pub_date', models.DateField(db_index=True, default=datetime.date.today, help_text='Date to be published', verbose_name='Published Date')),
                ('status', models.CharField(choices=[('H', 'Hidden'), ('D', 'Draft'), ('P', 'Published')], default='D', help_text='Hidden is publicly available, but not a part of the nav or lists. Draft hides it from unauthenticated users.', max_length=1, verbose_name='Status')),
                ('title', models.CharField(max_length=255)),
                ('title_en', models.CharField(max_length=255, null=True)),
                ('title_ar', models.CharField(max_length=255, null=True)),
                ('title_bn', models.CharField(max_length=255, null=True)),
                ('title_fr', models.CharField(max_length=255, null=True)),
                ('title_es', models.CharField(max_length=255, null=True)),
                ('slug', models.SlugField(max_length=255, unique=True)),
                ('meta_data', models.TextField(null=True)),
                ('meta_data_en', models.TextField(null=True)),
                ('meta_data_ar', models.TextField(null=True)),
                ('meta_data_bn', models.TextField(null=True)),
                ('meta_data_fr', models.TextField(null=True)),
                ('meta_data_es', models.TextField(null=True)),
                ('description', models.TextField(null=True)),
                ('description_en', models.TextField(null=True)),
                ('description_ar', models.TextField(null=True)),
                ('description_bn', models.TextField(null=True)),
                ('description_fr', models.TextField(null=True)),
                ('description_es', models.TextField(null=True)),
                ('location', models.TextField(null=True)),
                ('location_en', models.TextField(null=True)),
                ('location_ar', models.TextField(null=True)),
                ('location_bn', models.TextField(null=True)),
                ('location_fr', models.TextField(null=True)),
                ('location_es', models.TextField(null=True)),
                ('neighborhood', models.TextField(null=True)),
                ('neighborhood_en', models.TextField(null=True)),
                ('neighborhood_ar', models.TextField(null=True)),
                ('neighborhood_bn', models.TextField(null=True)),
                ('neighborhood_fr', models.TextField(null=True)),
                ('neighborhood_es', models.TextField(null=True)),
                ('link', models.CharField(max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255, null=True)),
                ('name_ar', models.CharField(max_length=255, null=True)),
                ('name_bn', models.CharField(max_length=255, null=True)),
                ('name_fr', models.CharField(max_length=255, null=True)),
                ('name_es', models.CharField(max_length=255, null=True)),
                ('agency', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='programs.Agency')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.Program'),
        ),
        migrations.AlterUniqueTogether(
            name='program',
            unique_together=set([('agency', 'name')]),
        ),
    ]
