# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-01 11:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='location_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='meta_data_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='neighborhood_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='title_ru',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
