# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-04 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0002_auto_20190301_1135'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientAverage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='1 appears before 2', verbose_name='Order')),
                ('name', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('latitude', models.CharField(blank=True, max_length=255)),
                ('longitude', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Population',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='1 appears before 2', verbose_name='Order')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('name_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('name_es', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ('order',),
            },
        ),
        migrations.CreateModel(
            name='ProgramType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='1 appears before 2', verbose_name='Order')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('name_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('name_es', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ('order',),
            },
        ),
        migrations.RemoveField(
            model_name='program',
            name='location',
        ),
        migrations.RemoveField(
            model_name='program',
            name='location_ar',
        ),
        migrations.RemoveField(
            model_name='program',
            name='location_bn',
        ),
        migrations.RemoveField(
            model_name='program',
            name='location_en',
        ),
        migrations.RemoveField(
            model_name='program',
            name='location_es',
        ),
        migrations.RemoveField(
            model_name='program',
            name='location_fr',
        ),
        migrations.RemoveField(
            model_name='program',
            name='location_ru',
        ),
        migrations.AddField(
            model_name='location',
            name='program',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.Program'),
        ),
        migrations.AddField(
            model_name='program',
            name='average_yearly_clients',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.ClientAverage'),
        ),
        migrations.AddField(
            model_name='program',
            name='populations_served',
            field=models.ManyToManyField(blank=True, null=True, to='programs.Population'),
        ),
        migrations.AddField(
            model_name='program',
            name='program_types',
            field=models.ManyToManyField(blank=True, null=True, to='programs.ProgramType'),
        ),
    ]
