# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-05 09:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0003_auto_20190304_1220'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='program',
        ),
        migrations.AddField(
            model_name='program',
            name='latitude',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='program',
            name='longitude',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.DeleteModel(
            name='Location',
        ),
    ]
