# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-06 14:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0006_auto_20190306_1034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='location_file',
        ),
        migrations.AddField(
            model_name='location',
            name='agency_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='location',
            name='program_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
