# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-14 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0007_auto_20190306_1432'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='agency_name',
        ),
        migrations.RemoveField(
            model_name='location',
            name='program_name',
        ),
    ]
