# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-03-22 13:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0008_auto_20190314_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='title',
        ),
        migrations.RemoveField(
            model_name='location',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='location',
            name='title_bn',
        ),
        migrations.RemoveField(
            model_name='location',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='location',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='location',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='location',
            name='title_ru',
        ),
        migrations.RemoveField(
            model_name='location',
            name='tooltip_content',
        ),
        migrations.RemoveField(
            model_name='location',
            name='tooltip_content_ar',
        ),
        migrations.RemoveField(
            model_name='location',
            name='tooltip_content_bn',
        ),
        migrations.RemoveField(
            model_name='location',
            name='tooltip_content_en',
        ),
        migrations.RemoveField(
            model_name='location',
            name='tooltip_content_es',
        ),
        migrations.RemoveField(
            model_name='location',
            name='tooltip_content_fr',
        ),
        migrations.RemoveField(
            model_name='location',
            name='tooltip_content_ru',
        ),
    ]
