# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-01 17:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0009_auto_20190322_1315'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='1 appears before 2', verbose_name='Order')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ar', models.CharField(blank=True, max_length=255, null=True)),
                ('name_bn', models.CharField(blank=True, max_length=255, null=True)),
                ('name_fr', models.CharField(blank=True, max_length=255, null=True)),
                ('name_es', models.CharField(blank=True, max_length=255, null=True)),
                ('name_ru', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
                'ordering': ('order',),
            },
        ),
        migrations.RemoveField(
            model_name='program',
            name='neighborhood_ar',
        ),
        migrations.RemoveField(
            model_name='program',
            name='neighborhood_bn',
        ),
        migrations.RemoveField(
            model_name='program',
            name='neighborhood_en',
        ),
        migrations.RemoveField(
            model_name='program',
            name='neighborhood_es',
        ),
        migrations.RemoveField(
            model_name='program',
            name='neighborhood_fr',
        ),
        migrations.RemoveField(
            model_name='program',
            name='neighborhood_ru',
        ),
        migrations.AlterField(
            model_name='program',
            name='neighborhood',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='programs.Neighborhood'),
        ),
    ]
