# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-02 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0010_auto_20190401_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='program',
            old_name='title',
            new_name='display_name',
        ),
        migrations.RemoveField(
            model_name='program',
            name='meta_data',
        ),
        migrations.RemoveField(
            model_name='program',
            name='meta_data_ar',
        ),
        migrations.RemoveField(
            model_name='program',
            name='meta_data_bn',
        ),
        migrations.RemoveField(
            model_name='program',
            name='meta_data_en',
        ),
        migrations.RemoveField(
            model_name='program',
            name='meta_data_es',
        ),
        migrations.RemoveField(
            model_name='program',
            name='meta_data_fr',
        ),
        migrations.RemoveField(
            model_name='program',
            name='meta_data_ru',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_ar',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_bn',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_en',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_es',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_fr',
        ),
        migrations.RemoveField(
            model_name='program',
            name='title_ru',
        ),
    ]
