# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-02 16:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0012_auto_20190402_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agency',
            name='name_ar',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='name_bn',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='name_en',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='name_es',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='name_fr',
        ),
        migrations.RemoveField(
            model_name='agency',
            name='name_ru',
        ),
        migrations.AddField(
            model_name='agency',
            name='display_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='display_name_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='display_name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='display_name_en',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='display_name_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='display_name_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='display_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
