# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-10 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0014_auto_20190408_1348'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='program',
            name='neighborhood',
        ),
        migrations.AddField(
            model_name='program',
            name='neighborhood',
            field=models.ManyToManyField(null=True, to='programs.Neighborhood'),
        ),
    ]
