# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-04-17 13:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0015_auto_20190410_1624'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProgramLink',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Created at')),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True, verbose_name='Updated at')),
                ('url', models.CharField(max_length=255)),
                ('label', models.CharField(max_length=255)),
                ('label_en', models.CharField(max_length=255, null=True)),
                ('label_ar', models.CharField(max_length=255, null=True)),
                ('label_bn', models.CharField(max_length=255, null=True)),
                ('label_fr', models.CharField(max_length=255, null=True)),
                ('label_es', models.CharField(max_length=255, null=True)),
                ('label_zh_hant', models.CharField(max_length=255, null=True)),
                ('label_ht', models.CharField(max_length=255, null=True)),
                ('label_ko', models.CharField(max_length=255, null=True)),
                ('label_ru', models.CharField(max_length=255, null=True)),
                ('label_ur', models.CharField(max_length=255, null=True)),
                ('program', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='programs.Program')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
