# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-08 16:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0016_programlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='display_name_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='workforce_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='name_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='population',
            name='name_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='display_name_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='workforce_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='programlink',
            name='label_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programtype',
            name='name_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
