# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-05-29 07:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0017_auto_20190508_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='agency',
            name='workforce_id',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='program',
            name='workforce_id',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
