# Generated by Django 2.2 on 2022-11-29 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('programs', '0021_auto_20220322_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='agency',
            name='display_name_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='display_name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='display_name_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='display_name_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='display_name_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='display_name_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='display_name_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='display_name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='display_name_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='agency',
            name='display_name_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='name_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='name_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='name_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='name_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='name_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='name_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='neighborhood',
            name='name_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='population',
            name='name_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='population',
            name='name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='population',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='population',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='population',
            name='name_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='population',
            name='name_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='population',
            name='name_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='population',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='population',
            name='name_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='population',
            name='name_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description_ar',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description_bn',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description_es',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description_fr',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description_ht',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description_ko',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description_pl',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description_ru',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description_ur',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='description_zh_hant',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='display_name_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='display_name_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='display_name_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='display_name_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='display_name_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='display_name_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='display_name_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='display_name_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='display_name_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='program',
            name='display_name_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programlink',
            name='label_ar',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programlink',
            name='label_bn',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programlink',
            name='label_es',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programlink',
            name='label_fr',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programlink',
            name='label_ht',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programlink',
            name='label_ko',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programlink',
            name='label_pl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programlink',
            name='label_ru',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programlink',
            name='label_ur',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programlink',
            name='label_zh_hant',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programtype',
            name='name_ar',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programtype',
            name='name_bn',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programtype',
            name='name_es',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programtype',
            name='name_fr',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programtype',
            name='name_ht',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programtype',
            name='name_ko',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programtype',
            name='name_pl',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programtype',
            name='name_ru',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programtype',
            name='name_ur',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='programtype',
            name='name_zh_hant',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
